### ISSUE TITLE
popen2 is missing for Python3

### ISSUE THREAD

**Issue by sibskull** [AGProjects/python3-eventlib#1]
$ python3 processes_test.py
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/eventlib-0.3.0/greentest/processes_test.py", line 25, in <module>
    from eventlib import processes
  File "/usr/lib/python3/site-packages/eventlib/processes.py", line 22, in <module>
    import popen2
ModuleNotFoundError: No module named 'popen2'

Please, rewrite implementation of processes handling from popen2 to subprocess.Popen: https://stackoverflow.com/questions/3892556/subprocess-replacement-of-popen2-with-python

**Comment by sibskull** [comment]
Quick patch:
```diff --git a/eventlib/processes.py b/eventlib/processes.py
index bdc1349..6355617 100644
--- a/eventlib/processes.py
+++ b/eventlib/processes.py
@@ -19,7 +19,7 @@
 
 import errno
 import os
-import popen2
+import subprocess
 import signal
 
 from eventlib import coros
@@ -98,10 +98,10 @@ class Process(object):
         self.popen4 = None
 
         ## We use popen4 so that read() will read from either stdout or stderr
-        self.popen4 = popen2.Popen4([self.command] + self.args)
+        self.popen4 = subprocess.Popen([self.command] + self.args, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, close_fds=True)
         self.event = _add_child_pobj(self.popen4)
-        child_stdout_stderr = self.popen4.fromchild
-        child_stdin = self.popen4.tochild
+        child_stdout_stderr = self.popen4.stdout
+        child_stdin = self.popen4.stdin
         greenio.set_nonblocking(child_stdout_stderr)
         greenio.set_nonblocking(child_stdin)
         self.child_stdout_stderr = greenio.GreenPipe(child_stdout_stderr)```

**Comment by tijmenNL** [comment]
Thanks for the patch. I applied it, but I removed shell=True. See 67d2065

**Comment by sibskull** [comment]
Thanks.
